name: Release

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
    inputs:
     ignore_blocks:
        description: 'Ignore blocking PRs/issues'
        type: boolean
        required: true
        default: false

defaults:
  run:
    shell: bash

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes since last release
        uses: actions/github-script@v7
        with:
          script: |
            const tags = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            if (tags.data.length === 0) {
              core.info('No tags found, skipping check for changes.');
              return;
            }
            const latestTag = tags.data[0].name;
            const commits = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: latestTag,
              head: 'HEAD',
            });
            if (commits.data.files.length === 0) {
              core.setFailed('No changes detected since last release.');
            }

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          release_branches: main

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.AFETCH_RELEASE_PAT }}
          TAG: ${{ steps.tag_version.outputs.new_tag }}
